// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Url struct {
	ID         int64      `json:"id"`
	ShortCode  string     `json:"short_code"`
	LongUrl    string     `json:"long_url"`
	ClickCount int64      `json:"click_count"`
	ExpiresAt  *time.Time `json:"expires_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}
