// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteExpiredURLs(ctx context.Context) error
	GetURLByCode(ctx context.Context, shortCode string) (Url, error)
	// used to dedup: if the same long_url was shortened before, reuse the code
	GetURLByLongURL(ctx context.Context, longUrl string) (Url, error)
	IncrementClickCount(ctx context.Context, shortCode string) error
}

var _ Querier = (*Queries)(nil)
