// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package sqlc

import (
	"context"
	"time"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_code, long_url, expires_at)
VALUES ($1, $2, $3)
RETURNING id, short_code, long_url, click_count, expires_at, created_at, updated_at
`

type CreateURLParams struct {
	ShortCode string     `json:"short_code"`
	LongUrl   string     `json:"long_url"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.LongUrl, arg.ExpiresAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredURLs = `-- name: DeleteExpiredURLs :exec
DELETE FROM urls
WHERE expires_at IS NOT NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredURLs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredURLs)
	return err
}

const getURLByCode = `-- name: GetURLByCode :one
SELECT id, short_code, long_url, click_count, expires_at, created_at, updated_at FROM urls
WHERE short_code = $1
`

func (q *Queries) GetURLByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLByLongURL = `-- name: GetURLByLongURL :one
SELECT id, short_code, long_url, click_count, expires_at, created_at, updated_at FROM urls
WHERE long_url = $1
LIMIT 1
`

// used to dedup: if the same long_url was shortened before, reuse the code
func (q *Queries) GetURLByLongURL(ctx context.Context, longUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByLongURL, longUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE urls
SET click_count = click_count + 1,
    updated_at = now()
WHERE short_code = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementClickCount, shortCode)
	return err
}
